source {E:/Program Files/Xilinx/data/projnav/scripts/VsimStopServer.tcl}
-- Auto Generated by Project Navigator to simulate
-- HDL Bencher Annotated Test Bench
--
vlib work
onbreak {resume}
onerror {quit -code 99 -force}
onElabError {resume}
vcom -explicit  -93 "ctrl.vhd"
vcom -explicit  -93 "ROM32x32_3a2b.vhd.vhd"
vcom -explicit  -93 "ProgCnt.vhd"
vcom -explicit  -93 "PC_Update.vhd"
vcom -explicit  -93 "MUX2V5.vhd"
vcom -explicit  -93 "MUX2V32.vhd"
vcom -explicit  -93 "File_Regs.vhd"
vcom -explicit  -93 "DataMem.vhd"
vcom -explicit  -93 "ALU.vhd"
vcom -explicit  -93 "mips.vhf"
vcom -explicit  -93 "iface_s3.vhd"
vcom -explicit  -93 "mips_sys.vhf"
vcom -explicit  -93 "tb_sys.ant"
vsim -t 1ps   -lib work tb_sys
run -all
quit -force
